'use client';
import { useNewsletterStore } from '@/lib/newsletter/store';
import { createEventItem } from '@/lib/newsletter/defaults';
import type { EventGridBlock, EventItem } from '@/lib/newsletter/schema';
import type { GlobalSettings } from '@/lib/settings/schema';
import { HeaderInspector } from '../inspector/header-inspector';
import { ImageInspector } from '../inspector/image-inspector';
import { LockedBlockInspector } from '../inspector/locked-block-inspector';
import { TextInspector } from '../inspector/text-inspector';

function Field({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) {
  return <label className="block text-sm font-medium">{label}<input className="mt-1 w-full rounded border p-2" value={value || ''} onChange={(event) => onChange(event.target.value)} /></label>;
}
function Area({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) {
  return <label className="block text-sm font-medium">{label}<textarea className="mt-1 w-full rounded border p-2" value={value || ''} onChange={(event) => onChange(event.target.value)} /></label>;
}
function EventGridInspector({ block, onChange }: { block: EventGridBlock; onChange: (patch: Partial<EventGridBlock>) => void }) {
  const updateItem = (id: string, patch: Partial<EventItem>) => onChange({ items: block.items.map((item) => item.id === id ? { ...item, ...patch } : item) });
  return <div className="space-y-4"><Field label="Abschnittsüberschrift" value={block.heading} onChange={(heading)=>onChange({heading})}/><p className="text-sm text-slate-600">Gerade Event-Anzahlen werden zweispaltig dargestellt; bei ungerader Anzahl läuft das letzte Event über die volle Breite.</p>{block.items.map((item,index)=><div key={item.id} className="space-y-2 rounded border p-3"><div className="flex items-center justify-between"><strong className="text-sm">Event {index+1}</strong>{block.items.length>1&&<button className="text-sm text-red-700" onClick={()=>onChange({items:block.items.filter((entry)=>entry.id!==item.id)})}>Entfernen</button>}</div><Field label="Kategorie" value={item.category} onChange={(category)=>updateItem(item.id,{category})}/><Field label="Titel" value={item.title} onChange={(title)=>updateItem(item.id,{title})}/><Field label="Datum / Uhrzeit" value={item.date} onChange={(date)=>updateItem(item.id,{date})}/><Field label="Ort" value={item.location} onChange={(location)=>updateItem(item.id,{location})}/><Area label="Beschreibung" value={item.description} onChange={(description)=>updateItem(item.id,{description})}/><Field label="Button-Label" value={item.buttonLabel} onChange={(buttonLabel)=>updateItem(item.id,{buttonLabel})}/><Field label="Button-URL" value={item.buttonUrl} onChange={(buttonUrl)=>updateItem(item.id,{buttonUrl})}/></div>)}<button className="rounded bg-blue-700 px-3 py-2 text-sm text-white" onClick={()=>onChange({items:[...block.items,createEventItem()]})}>Event hinzufügen</button></div>;
}

export function InspectorPanel({ settings, readOnly = false }: { settings?: GlobalSettings; readOnly?: boolean }){
  const doc=useNewsletterStore(s=>s.doc), id=useNewsletterStore(s=>s.selectedId), update=useNewsletterStore(s=>s.update), del=useNewsletterStore(s=>s.delete), move=useNewsletterStore(s=>s.move);
  const b=doc.blocks.find(x=>x.id===id);
  if(readOnly)return <aside className="sticky top-0 h-screen w-96 overflow-y-auto border-l bg-white p-6"><h2 className="text-lg font-semibold">Schreibgeschützt</h2><p className="mt-2 text-sm text-slate-600">Dieser Newsletter wurde als versendet markiert und kann nicht mehr bearbeitet werden.</p></aside>;
  if(!b)return <aside className="sticky top-0 h-screen w-96 overflow-y-auto border-l bg-white p-6">Wähle einen Newsletter-Baustein aus, um seinen Inhalt zu bearbeiten.</aside>;
  return <aside className="sticky top-0 h-screen w-96 overflow-y-auto border-l bg-white p-6"><div className="mb-4 flex gap-2"><button onClick={()=>move(b.id,-1)} className="rounded border px-2">Nach oben</button><button onClick={()=>move(b.id,1)} className="rounded border px-2">Nach unten</button>{b.type!=='header'&&b.type!=='footer'&&<button onClick={()=>del(b.id)} className="rounded border px-2 text-red-700">Löschen</button>}</div>{b.type==='header'?<HeaderInspector block={b} settings={settings} onChange={(patch)=>update(b.id, patch as any)}/>:b.type==='footer'?<LockedBlockInspector/>:b.type==='text'?<TextInspector/>:b.type==='featuredEvent'?<div className="space-y-3"><Field label="Overline" value={b.overline} onChange={(overline)=>update(b.id,{overline} as any)}/><Field label="Titel" value={b.title} onChange={(title)=>update(b.id,{title} as any)}/><Field label="Datum / Uhrzeit" value={b.date} onChange={(date)=>update(b.id,{date} as any)}/><Area label="Beschreibung" value={b.description} onChange={(description)=>update(b.id,{description} as any)}/><Field label="Button-Label" value={b.buttonLabel} onChange={(buttonLabel)=>update(b.id,{buttonLabel} as any)}/><Field label="Button-URL" value={b.buttonUrl} onChange={(buttonUrl)=>update(b.id,{buttonUrl} as any)}/><Field label="Bild-URL optional" value={b.image?.src} onChange={(src)=>update(b.id,{image:{...(b.image||{decorative:false}),src}} as any)}/></div>:b.type==='quote'?<div className="space-y-3"><Area label="Zitat" value={b.quote} onChange={(quote)=>update(b.id,{quote} as any)}/><Field label="Autor" value={b.author} onChange={(author)=>update(b.id,{author} as any)}/><Field label="Rolle" value={b.role} onChange={(role)=>update(b.id,{role} as any)}/></div>:b.type==='sectionHeading'?<Field label="Abschnitt" value={b.label} onChange={(label)=>update(b.id,{label} as any)}/>:b.type==='eventGrid'?<EventGridInspector block={b} onChange={(patch)=>update(b.id,patch as any)}/>:b.type==='event'?<div className="space-y-3"><Field label="Titel" value={b.title} onChange={(title)=>update(b.id,{title} as any)}/><Field label="Datum" value={b.date} onChange={(date)=>update(b.id,{date} as any)}/><Field label="Ort" value={b.location} onChange={(location)=>update(b.id,{location} as any)}/><Area label="Kurzbeschreibung" value={b.description} onChange={(description)=>update(b.id,{description} as any)}/><Field label="Button-URL" value={b.buttonUrl} onChange={(buttonUrl)=>update(b.id,{buttonUrl} as any)}/><Field label="Button-Label" value={b.buttonLabel} onChange={(buttonLabel)=>update(b.id,{buttonLabel} as any)}/></div>:<ImageInspector block={b} onChange={(patch)=>update(b.id, patch as any)}/>}</aside>;
}
