import { z } from 'zod';
export const allowedUrl=(v:string)=>{try{const u=new URL(v);return ['https:','http:','mailto:'].includes(u.protocol)}catch{return false}};
const url=z.string().trim().refine(allowedUrl,'Nur http, https oder mailto erlaubt');
const base=z.object({id:z.string().min(1),locked:z.boolean().optional()});
export const tiptapDocSchema=z.object({type:z.literal('doc'),content:z.array(z.any()).optional()});
export const headerBlockSchema=base.extend({type:z.literal('header'),locked:z.literal(true),branding:z.string()});
export const footerBlockSchema=base.extend({type:z.literal('footer'),locked:z.literal(true),contact:z.string(),legal:z.string()});
export const textBlockSchema=base.extend({type:z.literal('text'),content:tiptapDocSchema});
const imageFields={assetId:z.string().optional(),src:url.optional().or(z.literal('')),alt:z.string().optional(),decorative:z.boolean().default(false),href:url.optional().or(z.literal(''))};
export const imageBlockSchema=base.extend({type:z.literal('image'),...imageFields}).superRefine((v,c)=>{if((v.src||v.assetId)&&!v.decorative&&!v.alt?.trim())c.addIssue({code:'custom',path:['alt'],message:'Alternativtext ist erforderlich.'})});
export const eventBlockSchema=base.extend({type:z.literal('event'),image:z.object(imageFields).optional(),title:z.string().min(1,'Titel ist erforderlich'),date:z.string().optional(),location:z.string().optional(),description:z.string().optional(),buttonLabel:z.string().optional(),buttonUrl:url.optional().or(z.literal(''))}).superRefine((v,c)=>{if(v.buttonUrl&&!v.buttonLabel?.trim())c.addIssue({code:'custom',path:['buttonLabel'],message:'Button-Label ist bei URL erforderlich.'}); if(v.image?.src&&!v.image.decorative&&!v.image.alt?.trim())c.addIssue({code:'custom',path:['image','alt'],message:'Alternativtext ist erforderlich.'})});
export const newsletterBlockSchema=z.discriminatedUnion('type',[headerBlockSchema,textBlockSchema,eventBlockSchema,imageBlockSchema,footerBlockSchema]);
export const newsletterDocumentSchema=z.object({schemaVersion:z.literal(1),title:z.string().min(1),blocks:z.array(newsletterBlockSchema).min(2)}).superRefine((d,c)=>{if(d.blocks[0]?.type!=='header')c.addIssue({code:'custom',path:['blocks',0],message:'Dokument muss mit Header beginnen'}); if(d.blocks.at(-1)?.type!=='footer')c.addIssue({code:'custom',path:['blocks'],message:'Dokument muss mit Footer enden'});});
export type NewsletterDocument=z.infer<typeof newsletterDocumentSchema>; export type NewsletterBlock=z.infer<typeof newsletterBlockSchema>; export type TextBlock=z.infer<typeof textBlockSchema>; export type EventBlock=z.infer<typeof eventBlockSchema>; export type ImageBlock=z.infer<typeof imageBlockSchema>;
export const isLocked=(b:NewsletterBlock)=>b.type==='header'||b.type==='footer'||b.locked===true;
